version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: keycloak-secrets
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:5432/postgres?currentSchema=keycloak&sslmode=require
      KC_DB_USERNAME: postgres.hfqrijwbxklnuaszsxmb
      KC_DB_PASSWORD: biteTheDust
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KC_DB_SCHEMA: keycloak
    ports:
      - '8080:8080'
    command:
      - start-dev
      - --db-schema=keycloak
    networks:
      - app-network
    mem_limit: 1024m
    mem_reservation: 512m
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    # healthcheck:
    #   test: ['CMD', 'curl', '-f', 'http://localhost:8080/health/ready']
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - keycloak
    mem_limit: 768m
    mem_reservation: 256m
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
